version: "2.1"
services:
  web:
    image: mondrupalimage
    build: ./
    container_name: drupal
    ports:
      - "8050:80"
    depends_on:
      mysql: 
        condition: service_healthy
    volumes:
      - ./site:/var/www/html

  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5  
   
